### ISSUE TITLE
xBRZ, xBR and Super xBR

### ISSUE THREAD

**Issue by ADormant** [crosire/reshade-shaders#12]
Can xBRZ texture scaler and xBR/Super xBR shader and texture scaler be ported to reshade?

https://github.com/tapcio/PeteOpenGL2Tweak/tree/master/gpuPeteOpenGL2Tweak/xBRZ
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1
https://sourceforge.net/projects/xbrz/files/xBRZ/
https://github.com/hrydgard/ppsspp/tree/master/ext/xbrz
https://github.com/hrydgard/ppsspp/pull/8338/files
https://github.com/PeterTh/gedosato/tree/master/ext/xbrz
https://github.com/libretro/common-shaders/tree/master/xbr
https://github.com/devinacker/bsnes-plus/pull/27/files
https://sourceforge.net/projects/xbrz/files/xBRZ/
https://sourceforge.net/projects/xbrz/files/?source=navbar
https://github.com/gonetz/GLideN64/commit/daf18efabbae16454c83562456a6cc19b53255a1
https://github.com/gonetz/GLideN64/commit/5bf7a4e4dea9bc7f1b0cb68db5781b386a5470b7
https://github.com/gonetz/GLideN64/commit/65f29beba6f32f6887647baf28bdae07ad515b96
https://github.com/gonetz/GLideN64/commit/b81c8404fed4a1eb62d3c7354fb7151d1be9508b
https://github.com/gonetz/GLideN64/commit/58c48a8f60e06b77c2dd5133f94b43f7a34218cd
https://github.com/gonetz/GLideN64/commit/663b5d1f5e930d755b157a68fc804f0372622584
https://github.com/Tinob/Ishiiruka/commit/d2fb92518f50c6154f33f05be39128e48d6b83be
https://github.com/Tinob/Ishiiruka/commit/84f96aec7b2c52fda401e9d2419ab9a8787b349a
https://github.com/Tinob/Ishiiruka/commit/6bf5062b7656d9d1d026478a2a639497cad2357b
http://ngemu.com/threads/peops-opengl-1-78-xbrz-scalers-mod.173953/
http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/
https://github.com/nagadomi/waifu2x
http://forum.doom9.org/showthread.php?t=170727

**Comment by ADormant** [comment]
https://github.com/tapcio/PeteOpenGL2Tweak/tree/master/gpuPeteOpenGL2Tweak/xBRZ

**Comment by ADormant** [comment]
http://pastebin.com/cbH8ZQQT

**Comment by timofonic** [comment]
Any news? It would be interesting to have one big place for shaders :)

**Comment by ADormant** [comment]
@crosire @JPulowski 
Super xBR scaler https://forums.dolphin-emu.org/attachment.php?aid=14516
http://pastebin.com/cbH8ZQQT
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1

**Comment by ADormant** [comment]
https://github.com/Tinob/Ishiiruka/commit/c9a5b9030bd4bfa260790df8f9c55d47a34319ca
Jinc2-Sharper 
@crosire @JPulowski

**Comment by crosire** [comment]
Please post these on the forum next time, so somebody interested enough might pick them up. It won't help here. I'm therefore closing the two issues for now.
