### ISSUE TITLE
Collection of shaders

### ISSUE THREAD

**Issue by ADormant** [crosire/reshade-shaders#15]
Good collection of shaders, would be nice if they could be ported to reshade.
http://forums.pcsx2.net/attachment.php?aid=59323
http://forums.pcsx2.net/attachment.php?aid=58713
http://forums.pcsx2.net/attachment.php?aid=58715
http://forums.pcsx2.net/attachment.php?aid=58724
http://forums.pcsx2.net/attachment.php?aid=58946
https://forums.dolphin-emu.org/attachment.php?aid=13173
https://forums.dolphin-emu.org/attachment.php?aid=13169

**Comment by ADormant** [comment]
http://forums.pcsx2.net/attachment.php?aid=58713
http://forums.pcsx2.net/attachment.php?aid=58715

**Comment by ADormant** [comment]
http://forums.pcsx2.net/attachment.php?aid=58711
http://forums.pcsx2.net/attachment.php?aid=58713
http://forums.pcsx2.net/attachment.php?aid=58715
http://forums.pcsx2.net/attachment.php?aid=58724

**Comment by ADormant** [comment]
@JPulowski @crosire 
In fact one very interesting storybook shader has already been ported to reshade so the only thing left is to add it to repository.

https://forums.dolphin-emu.org/attachment.php?aid=13169

**Comment by JPulowski** [comment]
I just started working on porting libretro shaders to ReShade. Few of them are done, the only thing remains is optimization before final release. Some others might need a redesign in the algorithm because of ReShade's limitations.

The shaders you have posted is a great find. I will try to port the ones that might be useful.

**Comment by ADormant** [comment]
Great thanks. Deposterize shader good for preventing banding.
https://github.com/libretro/common-shaders/commit/cc81b1fd425869c05091ae8bf1138ba3d42fa3a4

**Comment by ADormant** [comment]
http://forums.pcsx2.net/attachment.php?aid=58724

**Comment by ADormant** [comment]
@JPulowski Updated pack.
http://forums.pcsx2.net/attachment.php?aid=59008
