### ISSUE TITLE
HBAO Shader

### ISSUE THREAD

**Issue by ADormant** [crosire/reshade-shaders#16]
I found an open source HBAO shader it has higher quality than the SSAO shader in reshade. Could you port it to reshade.

https://gist.github.com/fisch0920/6770346
https://gist.github.com/search?utf8=%E2%9C%93&q=hbao

**Comment by ADormant** [comment]
https://gist.github.com/search?utf8=%E2%9C%93&q=hbao

**Comment by martymcmodding** [comment]
Relies on data not retrieveable by ReShade, such as projection matrices etc. Could be replaced by fake data at the cost of view stability. Wait for my own AO, when it comes out, no other AO will be needed, I think.

**Comment by ADormant** [comment]
@martymcmodding 
Found some other HBAOs
https://github.com/nvpro-samples/gl_ssao
https://github.com/scanberg/hbao
https://github.com/aiwl/hbao

**Comment by martymcmodding** [comment]
These are all implementations following the original Nvidia HBAO paper. I think I had a look at every available AO solution there is, even on extremely unknown ones like ABAO and PBAO where only asm source exist. Of course I can implement more and more and more AO shaders but why? There is nothing special about these ones in comparison to the HBAO that already is in the Framework, visual result will be no different at all. The only way to get better AO with ReShade is writing an own algorithm which is what I'm doing, CHeck this out:

https://www.youtube.com/watch?v=qyQ9J4wJzGU

Watch in Full HD and fullscreen for best result. This AO is faster than any other AO implementation, maybe except native DX11 Alchemy SAO but that's not possible on ReShade.

**Comment by ADormant** [comment]
@martymcmodding What ABAO, PBAO and MXAO acronyms stand for? ABAO and PBAO are indeed extremely rare there is nothing on the net about them.

**Comment by martymcmodding** [comment]
ABAO is Angle Based Ambient Occlusion, PBAO, idk, source is unclear but these were originally only available in Sikkmod for Doom 3 and they are in ASM. MXAO is short for "Marty's Extreme Ambient Occlusion" until I find a less cheesy name :p

**Comment by ADormant** [comment]
What is ASM?
