### ISSUE TITLE
Add Linux support ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [crosire/reshade-shaders#18]
Please, you already support openGL, please add Linux support for your awesome software :) 
And Linux is not only 1% of marketshare, it's far more and growing. 
Secondly adding Linux support will add Android, Chrome OS and steam OS support :)  because they are Linux based. This will also allow the use of your effects in cloud gaming and smart TVs /smart cars/internet of things Games. 
Oh and the next Nintendo NX (wii u successor) is rumored to be on a Linux. 
And maybe you can benefits of this port in becoming full crossplatform and be supported on OSX, BSDs, etc

**Comment by crosire** [comment]
Almost the entire ReShade core code is Windows-specific. Adding Linux support would be tremendous amount of work, which is not justified right now with the small amount who would actually benefit from it.
Either way, this repository is about the shaders for ReShade and not the ReShade injector itself. Please post such suggestions on the website next time =).

**Comment by timofonic** [comment]
There's interest in [Linux](http://reshade.me/forum/troubleshooting/546-linux-report-reshade-sweetfx-2-0-hint-fails).

Can't ReShade be made multiplatform in some way?

Can those shaders be used in non-Windows games and other kind of software?

RetroArch has a multiplatform approach:

- It uses Nvidia's [Cg shaders](https://github.com/libretro/RetroArch/wiki/Cg-shaders) for both OpenGL and DirectX environments: [see their gfx code]([](https://github.com/libretro/RetroArch/tree/master/gfx/))

- They developed a tool to convert from Cg to GSGL shaders: [Cg2Glsl](https://github.com/libretro/RetroArch/blob/master/tools/cg2glsl.py).

Theres tons of shaders, but dispersed over tons of websites and repositories. It would be optimal if they get eventually more documented, too.

https://gist.github.com/igv/a9a21ad1f6dd7d0b4452
https://github.com/peeweek/bizhawk-shaders
https://github.com/aybe/RetroArch-shaders
https://github.com/jblume/ntsc-filter-genplus
https://github.com/AdamWu/cocos2dx-extension/tree/master/resources/shader
https://github.com/Armada651/hqx-shader
https://github.com/jblume/ntsc-filter-genplus
https://github.com/OpenXRay/xray-16/tree/dev/res/gamedata/shaders/gl
https://github.com/JosephFiola/SaturdayShaders
https://github.com/keijiro/Retro3D
https://github.com/lawlessc/oliveretroshader
https://github.com/libretro/common-shaders


I think shaders and profilers would be used in Wine by adding some hooking system. Maybe it could be used to improve performance or fix game bugs/incompatibilities.

I understand making this project multiplatform is crazy, it would be a tremendous amount of work. But I think a multiplatform Open Source shaders repository and framework would benefit everyone:
-  Developers: A better organized and more collaborative friendly environment by the use of Git & GitHub could motivate a more fruitful community too.
  * Centralized repository and better organization.
  * Merged efforts, more bugtesting. 
- Users: 
  * Easier to find shaders: Maybe even provide a multiplatform shader repository & configuration tool available in many platforms.
  * Quality & Quantity: A stronger community coul potentially contribute on it. It could not only have better and more improved shaders, but able to use it in different software like video players and computer/console emulators too (my main interest.

How to make this possible? No idea, this is just a naive wishlist. I just see RetroArch provided shaders, [ScummVM](http://forums.scummvm.org/viewtopic.php?t=13692l) plans to have shaders too.

http://wiki.scummvm.org/index.php/OpenTasks/Generic/Extend_plugin_system
http://wiki.scummvm.org/index.php/OpenTasks/Graphics/Hardware_Acceleration
http://wiki.scummvm.org/index.php/TODO#General_3
http://singron.blogspot.com
http://www.rlauncher.com/forum/showthread.php?251-RetroArch-Module/page48

I'm sure you already know about this tons better than me, but just wanted to provide some "facts".

**Comment by crosire** [comment]
ReShade uses its own shader language called ReShade FX. Not HLSL, not CG. Anything written for ReShade cannot be droped somewhere else without extra work. And as I said, it's too much work currently.

**Comment by LifeIsStrange** [comment]
Also steam machines will be all Linux. 
And the Nintendo NX (which will use Vulkan) is supposed to be LiNuX. 
And Linux pc marketshare should grow because that the majority of future Games will be Vulkan based.

**Comment by LifeIsStrange** [comment]
@Crosire 
Will you port ReShade FX shader language for Vulkan ? Because spir-V can support every langage if ported. 
For exemple Python https://github.com/cheery/spirthon

 https://github.com/KhronosGroup/SPIRV-LLVM

**Comment by crosire** [comment]
I'll probably use the ReShade FX to GLSL backend and then compile the generated GLSL to SPIR-V.

**Comment by timofonic** [comment]
So what's the issue? RSFX -> GLSL or a possible SPIR-V backend if someone writes it.

What are the obstacles to make ReShade multiplatform? Would other projects interested in helping in rewriting ReShade FX to make it multiplatform shader backend?

**Comment by crosire** [comment]
The entire hooking procedure, ReShade's core is highly platform dependant. Generally the way the project is structured makes it currently impossible to port to anything other than Windows without major effort.

**Comment by timofonic** [comment]
I see, sorry. I just hope maybe enough joined efforts would make it possible over time. Graphics are an issue when making them multiplatform, shaders are "just" a way to do graphics processing in GPU and it's a shame it's yet not possible to have a cross-platform solution.

I'm sorry for my ignorance asking about this and the accidental spam....
