### ISSUE TITLE
Add common.cfg toggle for negative depth buffer and use it in Reshade.fx

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade-shaders#2]
Lots of games (well, more than a couple) have a negative depth buffer. It's very easy to add this for the user: a new RFX_NegativeDepth #define should be added to common.cfg (default 0) which affects a #ifdef in Reshade.fx, where it alters 'depth' in RFX_PS_StoreDepth. 

I'll add this tomorrow and send you a PR.

**Comment by Ganossa** [comment]
Yes, this was indeed requested by many. I hope you are okay with me adding it in already (though it is not particularly elegantly integrated).

**Comment by FransBouma** [comment]
Yeah no problem. I didn't have time yesterday to create the pull request. It's not really that much work (couple of lines)

**Comment by crosire** [comment]
I guess this can be closed now after 11f9982f6c2b610f7432e76d8fc2020d429f0467.

**Comment by FransBouma** [comment]
I made a comment on that code: the code committed subtracts the value from 1, but shouldn't it be simply negating it? I.e. if the value read from the depthbuffer is -0.4, it's resulting in 1.4, not 0.4.

**Comment by crosire** [comment]
The depth buffer should always contain values above or equal to zero. However, there is another mistake, it is not necessarily smaller than one, only after it has been linearized. So the substraction should occur after linearization and not before.

**Comment by FransBouma** [comment]
Ah! Makes sense, I was under the impression a negative depth buffer simply means further away is more negative! 

	FB

**Comment by Ganossa** [comment]
Indeed, fixed the location of the depth check to after the linearization.
