### ISSUE TITLE
can we custom Reshade Screenshot folder

### ISSUE THREAD

**Issue by bluelovers** [crosire/reshade-shaders#22]
can we custom Reshade Screenshot folder?

**Comment by crosire** [comment]
Yes: ```#pragma reshade screenshot_location "/path/to/folder/..."```
Again, this repository is about the shaders for ReShade, not ReShade itself.

**Comment by bluelovers** [comment]
it work on 1.x, but not work on 2.0.3f1 now

i try use, all fail

#pragma reshade screenshot_location "./Reshade_Screenshot"
#pragma reshade screenshot_location "C:/Program Files (Game)/Guild Wars 2/Reshade Screenshot"
#pragma reshade screenshot_location "C:\Program Files (Game)\Guild Wars 2\Reshade_Screenshot"
#pragma reshade screenshot_location "C:\Program Files (Game)\Guild Wars 2\Reshade Screenshot"

**Comment by crosire** [comment]
Make sure the folder already exists.

**Comment by bluelovers** [comment]
oops, thx, i use new pc,forgot create folder
