### ISSUE TITLE
It looks like my shaders are broken in v2

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade-shaders#23]
DepthHaze and Emphasize are either not working at all or only a tiny bit. 

I have no idea why, perhaps due to the new linearization of the depth buffer. :/

(edit) If I visualize the depth buffer it's empty, yet the DoF works fine! So something overwrites the depth buffer 

I'm using the latest version. Will look into whether this is related to anything I did. I'll start with a fresh install.

**Comment by FransBouma** [comment]
If I switch off linearization, show depth buffer shows a very dim image, so very low values. If I switch on linearization, depth buffer is empty (all black). DoF works fine. I'll now see what is shown with reshade 1.0, which I used before.

**Comment by FransBouma** [comment]
... aaaand it's a change in the negative->positive order of the depth buffer. In v1.0 things worked OK, but the same settings (defaults of v2.0) don't work: the depth buffer is reversed in ac syndicate it seems, which wasn't necessary for v1.0 reshade but it is in v2.0. 

I somehow missed that. WOrks fine now. All is well, case closed :)

**Comment by crosire** [comment]
1.0 did not have the "reversed" option and always assumed that by default. It's possible to encode the depth buffer on a logarithmic scale without reversing it however, which is why the option was added.

**Comment by FransBouma** [comment]
Ah that figures why I was so puzzled that I had to enabled it (and didn't do that at first)!
