### ISSUE TITLE
Suggestion (ReShade Assistant): game specific presets for (some) Reshade config vars.

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade-shaders#3]
A lot of gamers aren't very technical, and they therefore will find altering parameters problematic as they don't really know what to do with e.g. depth buffer settings and what a logarithmic buffer even is. As the mediator asks the user to browse to the game folder and pick the exe, it might be a good idea to ship a set of predefined values per well-known game exe. When the user then picks a well-known game exe, these settings are automatically applied. 

E.g. if the user picks witcher3.exe, the mediator enables logarithmic depth buffer, depth calc, so the user will not be puzzled when a depth buffer based effect doesn't work as expected. 

It's a lot of work to add info for all games (so no-one's going to do that ;)) but for a couple of well known and often played games where this matters it's perhaps a good idea. (e.g. GTAV, The Witcher3, FO4 etc.)

**Comment by Ganossa** [comment]
If we provide such (meta) data externally (e.g. in an additional file) which the ReShade Assistant (let's get used to the new name ;-)) can pick up, I agree to that proposal. We could use that file later for other game specific information if necessary.

**Comment by crosire** [comment]
Since this is not related to the topic of this repository, I'll close the issue.
