### ISSUE TITLE
ReShade Assistant.exe select non-exe file

### ISSUE THREAD

**Issue by bluelovers** [crosire/reshade-shaders#33]
some game launch by launcher

but at last it run as game.bin

than reshade will can't found profile
cos reshade try search folder name "game", not launcher

so i think need add can select all file type, not only exe file

----------------------

and can we add something like

`#if exists("./ReShade_APPLICATION.cfg")
	#include "./ReShade_APPLICATION.cfg"
#endif

#if !defined(__APPLICATION_NAME2__)
	#define __APPLICATION_NAME2__ __APPLICATION_NAME__
#endif`

make reshade can load Custom __APPLICATION_NAME__ for search profile folder?
(search this file on game folder)

-----------

and hope warning msg can show which profile is try search

`#warning "Could not find application profile, falling back to default"`

something like this

`#warning "Could not find application profile __APPLICATION_NAME__, falling back to default"`

**Comment by crosire** [comment]
No longer relevant due to restructure in ReShade 3.0.
