### ISSUE TITLE
Reshade 3.0 Motion Vector Buffer. (e.g. for Motion blur, Temporal AA etc).

### ISSUE THREAD

**Issue by YellowOnion** [crosire/reshade-shaders#35]
I think this needs access to vertex buffer (I'm not sure if this is possible?).

Motion estimation can also be used but might be too expensive to use.

This can help implement object based motion blur, and temporal AA techniques like SMAA T2x, and TSSAA.

**Comment by crosire** [comment]
There is no common technique for managing a velocity buffer in games. Most games do not even use one, so it's impossible for ReShade to give access to it.
Also, this is the shader repository, please use the ReShade website for suggestions on the injector.
