### ISSUE TITLE
4k and scaling

### ISSUE THREAD

**Issue by AppliedEllipsis** [crosire/reshade-shaders#6]
The application does not scale well on a 4k screen with Windows Scaling enabled.
Also your forum won't let me register. "Your message has been considered spam. Try to decrease your post size and outsource logs to services like pastebin."  Not sure what that means, but I assume it's blocking my VPN.  Won't disable it to submit a bug.

![reshade](https://cloud.githubusercontent.com/assets/2762714/11610764/2c0e364c-9b7a-11e5-92a7-7e1ebf3b5bdd.png)

**Comment by crosire** [comment]
This repository isn't the place for reports not related to the shaders it hosts.
