### ISSUE TITLE
Include newest Adaptive Sharpen version

### ISSUE THREAD

**Issue by aufkrawall** [crosire/reshade-shaders#8]
Hello,
bacondither has released the latest version as stable (e.g. less brightness increase):
http://forum.doom9.org/showthread.php?t=172131

Could you please port it to ReShade again, JPulowski? :)

**Comment by crosire** [comment]
Should already have happened in #7. Consindering that it's @bacondither's work we should put this into a separat namespace with his name though.

**Comment by aufkrawall** [comment]
Ok. However, the changelog still says:
"Updated to version 2015-11-17"
The original version from that date doesn't include the latest improvements regarding quality.

Btw: Is it possible that the shader pack zip download provided by GitHub comes with more properly formatted files? They have everything in just one line.

**Comment by crosire** [comment]
They are formatted properly. It's just that the Windows Notepad cannot read files with line feeds only (Unix style, \n). It only understands files with carriage return line feeds (Windows style, \r\n). Git uses the former by default. I'd suggest to use a different editor (Notepad++, Sublime Text, ...) which understands those.

Anyway. I'll repopen this until it's confirmed the newest version is used.

**Comment by ADormant** [comment]
@crosire Newest Adaptive-Sharpen https://github.com/libretro/common-shaders/tree/master/sharpen

**Comment by JPulowski** [comment]
@ADormant @aufkrawall I will update the code when I am no longer busy with real life stuff, don't worry. I need some time for this version because after porting the new version I also need to implement optimizations done by @bacondither in the previous version. In order to do that I need to take a closer look at the code structure.

You might also try asking @bacondither if you would like a faster update. He is the original developer of the shader, I just ported and maintained it initially.

**Comment by bacondither** [comment]
I'm going to update the code in a day or so.

**Comment by aufkrawall** [comment]
Thanks a lot for this (also to JPulowski)!
With very blurry AA, AS definitely gives a much better result than Lumasharpen. It would be great if some day it would only cost ~5% with fast GPUs.

**Comment by crosire** [comment]
Updated in 79ef51cc842b1a249af11ed10da0dd813786b79e.

**Comment by aufkrawall** [comment]
Great!
However, I have to wait with testing/feedback until the next ReShade version is available.

**Comment by timofonic** [comment]
Hello.

I accidentally found a few updated filters, very probably you are aware of them. But I'll write it somewhere before forgetting it, maybe it can be an useful reminder (or not).


 Adaptive sharpen One Pass got updated yesterday 
http://forum.doom9.org/showthread.php?p=1744468#post1744468

@igv's  FineSharpA.glsl. 12h ago 
https://gist.github.com/igv/a9a21ad1f6dd7d0b4452
(he submits shaders to mpv/mpv too)

**Comment by timofonic** [comment]
The first filter by ts1...

ast edited by ts1; 2nd April 2016 at 11:25. Reason: Backported some things from 2-pass shaders, compatible with linear-scaling/sigmoid-upscaling, added anti-ringing
